import { db } from "@/db";
import {
  icps,
  specificIcps,
  queries,
  type Icp,
  type SpecificIcp,
  type Query,
  type Platform,
} from "@/db/schema";
import { eq, and } from "drizzle-orm";
import type { ChatCompletionTool } from "openai/resources/chat/completions";
import { openai, DEFAULT_MODEL } from "@/lib/ai/openai";

/** Cheap model used for high-volume query generation. */
export const QUERY_CHEAP_MODEL = process.env.OPENAI_MODEL ?? "gpt-5.6-luna";

export const ICP_SYSTEM_PROMPT = `You are an elite B2B Go-To-Market & Ideal Customer Profile (ICP) Strategist for Alpha Search.

Your goal is to help the user build, structure, and refine high-converting Ideal Customer Profiles (ICPs) for lead generation and precision search.

When the user enters a query, niche, or business idea:
1. Extract and formulate a crisp, professional ICP:
   - "name": The user's original concept/search query (e.g. "B2B SaaS companies hiring remote React engineers").
   - "title": A concise, executive-level title (3-7 words, e.g. "Remote-First B2B SaaS Hiring Engineers").
   - "description": A structured, comprehensive breakdown generated by you covering:
     • Target Industry & Sub-Niches
     • Company Profile (Size, Revenue/Funding Stage, Geography)
     • Key Decision Makers & Buyer Personas
     • Core Pain Points & Triggers
     • Value Proposition & Strategic Angle
2. ALWAYS call the "save_or_update_icp" tool whenever you create or refine an ICP.
3. In your conversational message:
   - Briefly summarize the key highlights of the generated/updated ICP.
   - Ask 1-2 focused, high-impact clarifying questions to help refine it further (e.g. target geography, company headcount, specific tech stack, or budget constraints).
   - Inform the user they can review and request adjustments (up to 5 revision turns).

Keep your conversational tone sharp, intelligent, professional, and concise.`;

export const ICP_TOOLS: ChatCompletionTool[] = [
  {
    type: "function",
    function: {
      name: "save_or_update_icp",
      description:
        "Save a newly generated ICP or update an existing ICP in the database. Always call this when generating or refining an ICP.",
      parameters: {
        type: "object",
        properties: {
          icpId: {
            type: "string",
            description:
              "The ID of the existing ICP to update. Leave empty/null if creating a new ICP.",
          },
          title: {
            type: "string",
            description:
              "A crisp, punchy, professional title summarizing the ICP (3-7 words).",
          },
          name: {
            type: "string",
            description:
              "The original user search term / input concept for this ICP.",
          },
          description: {
            type: "string",
            description:
              "Detailed structured AI-generated description including Target Industry, Company Size/Stage, Buyer Personas, Core Pain Points, and Strategic Value Proposition.",
          },
        },
        required: ["title", "name", "description"],
        additionalProperties: false,
      },
    },
  },
];

export interface SaveIcpToolArgs {
  icpId?: string;
  title: string;
  name: string;
  description: string;
}

export async function executeSaveOrUpdateIcp(
  args: SaveIcpToolArgs,
  userId: string,
): Promise<Icp> {
  const { icpId, title, name, description } = args;

  if (icpId) {
    // Verify ownership and update
    const [existing] = await db
      .select()
      .from(icps)
      .where(and(eq(icps.id, icpId), eq(icps.userId, userId)))
      .limit(1);

    if (existing) {
      const [updated] = await db
        .update(icps)
        .set({
          title,
          name: name || existing.name,
          description,
          updatedAt: new Date(),
        })
        .where(and(eq(icps.id, icpId), eq(icps.userId, userId)))
        .returning();

      return updated;
    }
  }

  // Otherwise insert new ICP record
  const [created] = await db
    .insert(icps)
    .values({
      userId,
      title,
      name,
      description,
    })
    .returning();

  return created;
}

// ─── Specific ICP Generation ───────────────────────────────────────────────

export const SPECIFIC_ICP_SYSTEM_PROMPT = `You are an elite B2B Go-To-Market Strategist specialising in ICP segmentation.

You will receive:
1. User's Original Input / Solution (what the user offers and the problem they solve).
2. General ICP (title + description).

Your task is to derive 5 to 10 highly specific, realistic sub-personas (Specific ICPs) that are concrete subsets or variants of that general ICP.

For each Specific ICP produce:
- "name": A short, punchy label (3-8 words) identifying this niche audience.
- "description": 2-4 sentences covering who they are, their core pain point, what triggers their buying decision, and why they match the general ICP.
- "whatToSearch": 2-3 strategic sentences guiding what to search on social platforms to find posts where this persona is sharing a problem that the user's offering solves.
  CRITICAL: Do NOT provide generic industry labels or broad topic lists (e.g. do NOT say "Search for startup banking, innovation banking, commercial banking, venture banking...").
  Instead, focus on:
  • What specific problem, frustration, or bottleneck does this persona experience that the user's product/service solves?
  • What questions, complaints, or discussions do they post online (e.g. asking for recommendations, venting about current tools/partners, dealing with inefficiencies)?
  • What specific keywords or problem-trigger phrases will catch them actively seeking help or discussing the user's problem space?

Rules:
- Every Specific ICP must logically belong inside the General ICP's universe and connect to the problem the user solves.
- Make them meaningfully distinct from each other — no near-duplicates.
- Be concrete: name real verticals, roles, or business models where possible.
- ALWAYS call the "save_specific_icps" tool with all generated Specific ICPs in one call.
- Do not include any extra commentary outside the tool call.`;

export const SPECIFIC_ICP_TOOLS: ChatCompletionTool[] = [
  {
    type: "function",
    function: {
      name: "save_specific_icps",
      description:
        "Save the list of Specific ICPs derived from the General ICP. Call this once with all items.",
      parameters: {
        type: "object",
        properties: {
          specificIcps: {
            type: "array",
            minItems: 5,
            maxItems: 10,
            description: "Array of 5-10 Specific ICP objects.",
            items: {
              type: "object",
              properties: {
                name: {
                  type: "string",
                  description:
                    "Short, punchy label for this specific ICP (3-8 words).",
                },
                description: {
                  type: "string",
                  description:
                    "2-4 sentence description covering who they are, pain point, buying trigger, and ICP fit.",
                },
                whatToSearch: {
                  type: "string",
                  description:
                    "Strategic guidance on what to search to uncover posts where this persona is expressing problems, bottlenecks, or needs that the user's product solves. Avoid generic industry keywords; focus on problem signals and pain-point discussions.",
                },
              },
              required: ["name", "description", "whatToSearch"],
              additionalProperties: false,
            },
          },
        },
        required: ["specificIcps"],
        additionalProperties: false,
      },
    },
  },
];

export interface SpecificIcpItem {
  name: string;
  description: string;
  whatToSearch: string;
}

export async function generateAndSaveSpecificIcps(
  generalIcp: Icp,
  userId: string,
): Promise<SpecificIcp[]> {
  const modelName = process.env.OPENAI_MODEL || DEFAULT_MODEL;

  const userMessage = `User's Original Input / What Problem User Solves:
${generalIcp.name}

General ICP Title: ${generalIcp.title}

General ICP Description:
${generalIcp.description}

Derive 5-10 Specific ICPs from this General ICP now. Ensure that for each Specific ICP, "whatToSearch" focuses on how to find posts where this persona expresses the problem the user is solving, rather than broad industry labels.`;

  const completion = await openai.chat.completions.create({
    model: modelName,
    messages: [
      { role: "system", content: SPECIFIC_ICP_SYSTEM_PROMPT },
      { role: "user", content: userMessage },
    ],
    tools: SPECIFIC_ICP_TOOLS,
    tool_choice: { type: "function", function: { name: "save_specific_icps" } },
    reasoning_effort: "none",
  });

  const message = completion.choices[0]?.message;
  if (!message?.tool_calls?.length) {
    throw new Error("AI did not return specific ICPs tool call.");
  }

  const toolCall = message.tool_calls[0] as {
    function: { arguments: string };
  };
  const parsed = JSON.parse(toolCall.function.arguments || "{}") as {
    specificIcps: SpecificIcpItem[];
  };

  if (!parsed.specificIcps?.length) {
    throw new Error("AI returned empty specific ICPs list.");
  }

  // Bulk-insert all specific ICPs linked to the general ICP
  const inserted = await db
    .insert(specificIcps)
    .values(
      parsed.specificIcps.map((item) => ({
        icpId: generalIcp.id,
        userId,
        name: item.name,
        description: item.description,
        whatToSearch: item.whatToSearch,
      })),
    )
    .returning();

  return inserted;
}

// ─── Query Generation (One-by-One per Specific ICP) ─────────────────────────

export const SINGLE_QUERY_SYSTEM_PROMPT = `You are a B2B lead-generation search expert for Alpha Search.

You will receive details for a persona to search for:
- User's Original Input / Problem Being Solved (the user's core solution, product, or initial concept)
- Parent General ICP context (if available)
- Specific ICP Name
- Specific ICP Description
- What to Search (guidance on discovering posts where this persona expresses the problem the user solves)

Your task is to generate high-intent, targeted platform search queries to find prospective leads on social platforms.

CORE OBJECTIVE: PROBLEM & PAIN-POINT DISCOVERY (AVOID GENERIC QUERIES)
- NEVER generate broad, generic industry terms on their own (e.g. avoid queries like "startup banking", "fintech", or "venture banking"). Broad terms return press releases and marketing articles, NOT leads.
- The PRIMARY FOCUS must be finding posts where people in this persona are trying to share, ask about, or solve a problem that the user's business solves.
- Look for posts where they are:
  • Expressing frustration, bottlenecks, or complaints about their current setup.
  • Asking peers for recommendations, alternatives, or advice.
  • Discussing operational struggles, churn, compliance, delays, or tooling issues.
- Connect the persona/niche with their pain-point or problem signals.

Platform Rules:
- linkedin, x, reddit: MUST generate 1 to 3 search queries for EACH of these three platforms without exception.
- hackernews: Generate 1 to 2 search queries whenever this Specific ICP relates to tech, software, startups, SaaS, founders, developer tools, AI, engineering, product, or remote business. (Only skip for purely non-tech/offline niches).
- github: OPTIONAL. Only generate queries for github if this Specific ICP is engineering, developer, technical, or open-source oriented.
- Do NOT generate queries for any other platforms.

CRITICAL QUERY FORMAT & SIMPLICITY RULES (MANDATORY):
1. ABSOLUTELY NO Boolean Operators or Parentheses:
   - Do NOT use AND, OR, NOT in the query string.
   - Do NOT use parentheses () in the query string.
   - Do NOT use platform field filters or qualifiers (e.g. NO title:, selftext:, subreddit:, in:title:, lang:, -is:retweet, etc.).

2. Strict Part Structure (MAX 2 PARTS, PREFERABLY 1 PART):
   A query part is either a quoted phrase like "startup banking" or an unquoted keyword/phrase like acquisition.
   - Rule A: The query should preferably have ONLY 1 part.
     - Example (1 part): "startup banking"
     - Example (1 part): "lead generation"
     - Example (1 part): fintech
   - Rule B: If the query has 2 parts, EXACTLY ONE part must be in double quotes "" and the OTHER part must be WITHOUT quotes.
     - Example (2 parts): "startup banking" acquisition
     - Example (2 parts): "b2b saas" churn
     - Example (2 parts): founders "lead generation"
   - Rule C: NEVER have 3 or more parts!
     - ❌ FORBIDDEN (3 parts): "startup banking" "venture-backed" acquisition
     - ❌ FORBIDDEN (3 parts): "b2b" "saas" marketing
   - Rule D: NEVER have two quoted parts!
     - ❌ FORBIDDEN: "startup banking" "venture-backed"
   - Rule E: Keep words inside parts minimal!
     - Inside quotes "": Strictly 1 to 3 words maximum (e.g. "startup banking", "cold outreach").
     - Unquoted part: Strictly 1 to 2 words maximum (e.g. acquisition, churn).
     - Never use long sentences or wordy phrases.

3. Platform Specifics:
   - Hacker News: Algolia search does not support quotes in query strings. For Hacker News ONLY, always use 1 part with 1 to 3 plain unquoted keywords (e.g. startup banking or b2b saas). No quotes, no booleans.
   - LinkedIn, X (Twitter), Reddit, GitHub: Strictly use either 1 part (e.g. "startup banking") or 2 parts where one is in quotes and one is unquoted (e.g. "startup banking" acquisition). Never use boolean syntax or field qualifiers.

Query Types:
For each platform, supply queries covering:
1. Pain-point / Problem queries (Highest Priority): Queries targeting posts/discussions where this persona expresses a pain point, struggle, or bottleneck that the user's product/service solves.
2. Problem-intent / Solution-seeking queries: Queries targeting discussions where this persona is asking for recommendations, alternatives, or workflows related to the problem being solved.

For each query include:
- "platform": "linkedin" | "x" | "reddit" | "github" | "hackernews"
- "query": The exact search query string following the strict 1-part or 2-part rules above.
- "must": array of required keywords or phrases (for post-search filtering)
- "optional": array of additional keywords that boost relevance
- "negativeKeywords": array of terms that disqualify a result

General Rules:
- Be precise and commercially relevant — these queries will be used to find real leads discussing real problems.
- Leverage the User's Original Input and "What to Search" guidance to target the exact pain points being solved.
- ALWAYS call the "save_queries" tool with all generated queries in a single call.
- Do not add commentary outside the tool call.`;

export const SINGLE_QUERY_TOOLS: ChatCompletionTool[] = [
  {
    type: "function",
    function: {
      name: "save_queries",
      description:
        "Save generated platform search queries for this Specific ICP.",
      parameters: {
        type: "object",
        properties: {
          queries: {
            type: "array",
            description: "Array of query objects for the target platforms.",
            items: {
              type: "object",
              properties: {
                platform: {
                  type: "string",
                  enum: ["linkedin", "x", "reddit", "github", "hackernews"],
                  description: "The platform this query is designed for.",
                },
                query: {
                  type: "string",
                  description:
                    "The simple search query string: only 1 part (e.g. \"startup banking\" or fintech) or at most 2 parts where exactly one is in quotes and the other is unquoted (e.g. \"startup banking\" acquisition). NEVER use AND, OR, (), field filters, or 3+ parts.",
                },
                must: {
                  type: "array",
                  items: { type: "string" },
                  description: "Required keywords (boolean AND).",
                },
                optional: {
                  type: "array",
                  items: { type: "string" },
                  description: "Optional boost keywords (boolean OR).",
                },
                negativeKeywords: {
                  type: "array",
                  items: { type: "string" },
                  description: "Disqualifying keywords (boolean NOT).",
                },
              },
              required: [
                "platform",
                "query",
                "must",
                "optional",
                "negativeKeywords",
              ],
              additionalProperties: false,
            },
          },
        },
        required: ["queries"],
        additionalProperties: false,
      },
    },
  },
];

export interface SingleQueryItem {
  platform: Platform;
  query: string;
  must: string[];
  optional: string[];
  negativeKeywords: string[];
}

export async function generateQueriesForSingleSpecificIcp(
  specificIcp: SpecificIcp,
  userId: string,
  parentIcp?: Icp,
): Promise<Query[]> {
  let originalUserInput = "";
  let generalIcpTitle = "";
  let generalIcpDescription = "";

  let icp = parentIcp;
  if (!icp && specificIcp.icpId) {
    const [fetched] = await db
      .select()
      .from(icps)
      .where(eq(icps.id, specificIcp.icpId))
      .limit(1);
    icp = fetched;
  }

  if (icp) {
    originalUserInput = icp.name;
    generalIcpTitle = icp.title;
    generalIcpDescription = icp.description ?? "";
  }

  const userMessage = `${originalUserInput ? `User's Original Input (Problem Being Solved):\n${originalUserInput}\n\n` : ""}${generalIcpTitle ? `General ICP Context:\nTitle: ${generalIcpTitle}\n${generalIcpDescription}\n\n` : ""}Specific ICP Name: ${specificIcp.name}

Specific ICP Description:
${specificIcp.description ?? "N/A"}

What to Search Guidance:
${specificIcp.whatToSearch ?? "N/A"}

Generate platform search queries for this Specific ICP now. Remember:
- linkedin, x, and reddit are MUST.
- hackernews and github should be generated when relevant (hackernews for tech/startups/SaaS/founders, github for dev/engineering).
- PRIMARY FOCUS: Find posts where these people are trying to share or solve a problem that the user's offering solves. Do NOT generate broad generic industry labels!
- Strictly follow the query simplicity rules: NO AND, OR, (), or field filters. Maximum 1 or 2 parts (if 2 parts, exactly one in quotes and one unquoted, e.g. "startup banking" acquisition). Very few words per part.`;

  const completion = await openai.chat.completions.create({
    model: QUERY_CHEAP_MODEL,
    messages: [
      { role: "system", content: SINGLE_QUERY_SYSTEM_PROMPT },
      { role: "user", content: userMessage },
    ],
    tools: SINGLE_QUERY_TOOLS,
    tool_choice: { type: "function", function: { name: "save_queries" } },
    reasoning_effort: "none",
  });

  const message = completion.choices[0]?.message;
  if (!message?.tool_calls?.length) {
    throw new Error(
      `AI did not return query tool call for ICP "${specificIcp.name}".`,
    );
  }

  const toolCall = message.tool_calls[0] as { function: { arguments: string } };
  const parsed = JSON.parse(toolCall.function.arguments || "{}") as {
    queries: SingleQueryItem[];
  };

  if (!parsed.queries?.length) {
    throw new Error(
      `AI returned empty queries list for ICP "${specificIcp.name}".`,
    );
  }

  const validPlatforms = new Set<string>([
    "linkedin",
    "x",
    "reddit",
    "github",
    "hackernews",
  ]);
  const validRows = parsed.queries.filter((r) =>
    validPlatforms.has(r.platform),
  );

  if (!validRows.length) {
    throw new Error(
      `AI returned no valid queries for ICP "${specificIcp.name}".`,
    );
  }

  // DEFAULT_RATING = 70 (representing 0.70 on a 0-100 integer scale)
  const DEFAULT_RATING = 70;

  const inserted = await db
    .insert(queries)
    .values(
      validRows.map((r) => ({
        specificIcpId: specificIcp.id,
        userId,
        platform: r.platform as Platform,
        query: r.query || "",
        rating: DEFAULT_RATING,
        must: r.must,
        optional: r.optional,
        negativeKeywords: r.negativeKeywords,
      })),
    )
    .returning();

  return inserted;
}

export async function generateQueriesForSpecificIcps(
  specificIcpList: SpecificIcp[],
  userId: string,
): Promise<Query[]> {
  if (!specificIcpList.length) return [];

  // Fetch parent ICP once if all items share the same parent
  const parentIcpId = specificIcpList[0]?.icpId;
  let parentIcp: Icp | undefined = undefined;
  if (parentIcpId) {
    const [fetched] = await db
      .select()
      .from(icps)
      .where(eq(icps.id, parentIcpId))
      .limit(1);
    parentIcp = fetched;
  }

  const allQueries: Query[] = [];
  for (const sIcp of specificIcpList) {
    const saved = await generateQueriesForSingleSpecificIcp(
      sIcp,
      userId,
      parentIcp,
    );
    allQueries.push(...saved);
  }

  return allQueries;
}
